#!/usr/bin/env bash
#Mamed Masalli
count=1
while [ $count -lt 101 ]
do
	if ((count%3== 0))
	then 
		echo "Fizz"
	else
		echo $count
	fi
	if ((count%5== 0))
	then	
		echo "Buzz"
	else
		echo $count
	fi
	if ((count%15== 0))
	then
		echo "FizzBuzz"
	fi
	((count++))
done	
