#!/usr/bin/env bash
#Mamed Masalli
count=1
while [ $count -lt 101 ]
do
	if [ $count%3 -eq 0 ]
	then 
		echo "Fizz"
	else
		echo count
	fi
	if [ $count%5 -eq 0 ]
	then	
		echo "Buzz"
	else
		echo count
	fi
	if [ $count%15 -eq 0]
	then
		echo "FizzBuzz"
	fi
	((count++))
done	
