#!/usr/bin/env bash
#Heyder
awk '{print $1, $9}' apache-access.log | awk '
$1=="127.0.0.1" && $2=="200"{a++}
$1=="192.168.1.10" && $2=="403"{b++}
END {
    print a, "127.0.0.1 200"
    print b, "192.168.1.10 403"
}'



