#!/usr/bin/env bash
#Heyder
LOG_FILE="apache-access.log"

awk '
{ count[$1" "$9]++ }
END {
    n = asorti(count, sorted_count, "@val_num_desc")
    for (i = 1; i <= n; i++) {
        split(sorted_count[i], arr, SUBSEP)
        ip_code = sorted_count[i]
        print count[ip_code], ip_code
    }
}
' "$LOG_FILE"
