#!/usr/bin/env bash
#RCL
count=1

while [ $count -lt 11 ]
do 
	echo "Best School"
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	fi
	if [ $count -eq 8 ]
	then 
		echo "good luck"
	fi
	((count++))
done
