#!/usr/bin/env bash
#QULI
count=1

while [ $count -lt 21 ]
do
	echo $count
	case [ $count -eq 4 ]
		echo $count
		echo "bad luck from China"
	esac
	case [ $count -eq 9 ]
		echo $count
		echo "bad luck from Japan"
	esac
	case [ $count -eq 17 ]
		echo $count
		echo "bad luck from Italy"
	esac
	((count++))
done
