#!/usr/bin/env bash
#1
pid=$(ps aux | grep '[4]-to_infinity_and_beyond' | awk '{print $2}')

if [ -n "$pid" ]; then
    kill "$pid"
    echo "Process $pid stopped."
else
    echo "Process not found."
fi

